#include "windows.h"
#define IDM_LOADBMP   1
#define IDM_EXIT      2 

#define ID_XOFFSET                      302
#define ID_YOFFSET                      303
#define ID_ANGLE                        304
#define ID_ZOOMRATIO                    305
#define ID_SECONDPOINT                  306
#define ID_STRETCHRATIO                 307
#define ID_FIRSTPOINT                   308
#define ID_EQUASCALE                    309
#define IDM_TRANSLATION                 40001
#define IDM_ROTATION                    40002
#define IDM_MIRRORX                     40003
#define IDM_MIRRORY                     40004
#define IDM_TRANSPOSE                   40005
#define IDM_ZOOM                        40006
#define IDM_SMOOTHING_BOX               40007
#define IDM_SMOOTHING_GAUSS             40008
#define IDM_SHARPENING_LAPLACIAN        40009
#define IDM_LIMBPATTERN                 40010
#define IDM_LIMBPATTERNM3               40010
#define IDM_REGUDITHER                  40011
#define IDM_FLOYD                       40012
#define IDM_STEINBERG                   40012
#define IDM_CLRGRAY                     40013
#define IDM_INVERT                      40014
#define IDM_LIMBPATTERNM4               40015
#define IDM_BMP2TXT                     40016
#define IDM_TRUE256                     40017
#define IDM_HISTOGRAM                   40018
#define IDM_CONTSTRETCH                 40019
#define IDM_CLIPING                     40020
#define IDM_THRESHOLD                   40021
#define IDM_SLICEWITHOUTBACK            40022
#define IDM_SLICEWITHBACK               40023
#define IDM_HISTOGRAMEQUA               40024
#define IDM_HDILATION                   40025
#define IDM_VDILATION                   40026
#define IDM_HEROSION                    40027
#define IDM_VEROSION                    40028
#define IDM_HOPEN                       40031
#define IDM_VOPEN                       40032
#define IDM_HCLOSE                      40033
#define IDM_VCLOSE                      40034
#define IDM_THINNING                    40035
#define IDM_OUTLINE                     40036
#define IDM_HSOBEL                      40037
#define IDM_VSOBEL                      40038
#define IDM_HISOSOBEL                   40040
#define IDM_VISOSOBEL                   40041
#define IDM_HVISOSOBEL                  40043
#define IDM_HOUGH                       40044
#define IDM_HMEDIAN                     40046
#define IDM_VMEDIAN                     40047
#define IDM_LOG                         40048
#define IDM_CONTOUR                     40049
#define IDM_HPROJECTION                 40050
#define IDM_VPROJECTION                 40051
#define IDM_SUBTRACTION                 40052
#define IDM_SEEDFILL                    40053
#define IDM_RUNLENGTH                   40056
#define IDC_STATIC                      65535

#define TEMPLATE_SMOOTH_BOX    1
#define TEMPLATE_SMOOTH_GAUSS  2
#define TEMPLATE_SHARPEN_LAPLACIAN 3
#define TEMPLATE_SOBEL_H 4
#define TEMPLATE_SOBEL_V 5
#define TEMPLATE_ISOSOBEL_H 6
#define TEMPLATE_ISOSOBEL_V 7
